# Generated by Django 4.1.7 on 2023-03-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_remove_book_auther_remove_bookvote_book1_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
